/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "chords.h"

void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim) {
    if (htim->Instance == TIM2) {          // your scanning timer
        chords_scan();
        // If you want to directly push chord to DAC, do it here:
        // uint8_t root;
        // ChordType type;
        // chords_get_current(&root, &type);
        // update_dac_chord(root, type);
    }
    // ...other callbacks...
}

int main(void)
{
    /* Loop forever */
    chords_init();
    HAL_TIM_Base_Start_IT(&htim2);   // assuming handle is htim2
	for(;;);
}
